# Generated by Django 3.2.9 on 2021-11-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='quotes', to='quotes.Tag'),
        ),
    ]
